# Generated by Django 4.0.2 on 2022-02-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezequiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ezequiel.directmessage'),
        ),
    ]
