# Generated by Django 4.0.2 on 2022-02-07 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezequiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_messages', to='ezequiel.directmessages')),
                ('replies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_replies', to='ezequiel.messages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
